services:
  - name: my-laravel-app
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: mfg
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: Conferenceapp
      - key: DB_USERNAME
        value: mfg
      - key: DB_PASSWORD
        sync: false
