services:
  - name: my-laravel-app
    type: web
    runtime: docker  # Utilisation de Docker pour Laravel
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql  # Si tu utilises PostgreSQL
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: conferenceapp
      - key: DB_USERNAME
        value: mfg
      - key: DB_PASSWORD
        sync: false  # Mets ton mot de passe dans l’interface Render
    startCommand: "php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT"
